[2021-06-06 23:22:02,337] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: create_rox_tables.create_specialofferproduct_table 2021-06-06T23:21:56.022314+00:00 [queued]>
[2021-06-06 23:22:02,357] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: create_rox_tables.create_specialofferproduct_table 2021-06-06T23:21:56.022314+00:00 [queued]>
[2021-06-06 23:22:02,357] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-06 23:22:02,357] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-06-06 23:22:02,360] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-06 23:22:02,378] {taskinstance.py:1087} INFO - Executing <Task(PostgresOperator): create_specialofferproduct_table> on 2021-06-06T23:21:56.022314+00:00
[2021-06-06 23:22:02,387] {standard_task_runner.py:52} INFO - Started process 126 to run task
[2021-06-06 23:22:02,390] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'create_rox_tables', 'create_specialofferproduct_table', '2021-06-06T23:21:56.022314+00:00', '--job-id', '27', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/create_rox_tables.py', '--cfg-path', '/tmp/tmpv70kieah', '--error-file', '/tmp/tmp2lf3764r']
[2021-06-06 23:22:02,391] {standard_task_runner.py:77} INFO - Job 27: Subtask create_specialofferproduct_table
[2021-06-06 23:22:02,433] {logging_mixin.py:104} INFO - Running <TaskInstance: create_rox_tables.create_specialofferproduct_table 2021-06-06T23:21:56.022314+00:00 [running]> on host 21bd802337aa
[2021-06-06 23:22:02,482] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_rox_tables
AIRFLOW_CTX_TASK_ID=create_specialofferproduct_table
AIRFLOW_CTX_EXECUTION_DATE=2021-06-06T23:21:56.022314+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-06-06T23:21:56.022314+00:00
[2021-06-06 23:22:02,482] {postgres.py:70} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS SpecialOfferProduct
    (
        SpecialOfferID INTEGER NOT NULL,
        ProductID INTEGER NOT NULL,
        rowguid VARCHAR(36),
        ModifiedDate TIMESTAMP,
        PRIMARY KEY (SpecialOfferID, ProductID),
        FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
    )
[2021-06-06 23:22:02,489] {base.py:78} INFO - Using connection to: id: redshift. Host: doxcluster.craeubgpe2r5.us-east-1.redshift.amazonaws.com, Port: 5439, Schema: dox, Login: doxuser, Password: ***, extra: {}
[2021-06-06 23:22:04,823] {dbapi.py:204} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS SpecialOfferProduct
    (
        SpecialOfferID INTEGER NOT NULL,
        ProductID INTEGER NOT NULL,
        rowguid VARCHAR(36),
        ModifiedDate TIMESTAMP,
        PRIMARY KEY (SpecialOfferID, ProductID),
        FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
    ), parameters: None
[2021-06-06 23:22:05,439] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 72, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 208, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "product" does not exist

[2021-06-06 23:22:05,442] {taskinstance.py:1531} INFO - Marking task as FAILED. dag_id=create_rox_tables, task_id=create_specialofferproduct_table, execution_date=20210606T232156, start_date=20210606T232202, end_date=20210606T232205
[2021-06-06 23:22:05,490] {local_task_job.py:151} INFO - Task exited with return code 1
