[2021-06-07 01:32:59,629] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: stage_rox_bike_tables.load_salesorderdetail_from_s3_to_redshift 2021-06-07T01:31:57.496009+00:00 [queued]>
[2021-06-07 01:32:59,638] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: stage_rox_bike_tables.load_salesorderdetail_from_s3_to_redshift 2021-06-07T01:31:57.496009+00:00 [queued]>
[2021-06-07 01:32:59,639] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-07 01:32:59,639] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-06-07 01:32:59,640] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-07 01:32:59,650] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): load_salesorderdetail_from_s3_to_redshift> on 2021-06-07T01:31:57.496009+00:00
[2021-06-07 01:32:59,655] {standard_task_runner.py:52} INFO - Started process 255 to run task
[2021-06-07 01:32:59,657] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'stage_rox_bike_tables', 'load_salesorderdetail_from_s3_to_redshift', '2021-06-07T01:31:57.496009+00:00', '--job-id', '77', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/stage_data_s3_to_redshift.py', '--cfg-path', '/tmp/tmpy_zl_qd1', '--error-file', '/tmp/tmp2ed90n5d']
[2021-06-07 01:32:59,657] {standard_task_runner.py:77} INFO - Job 77: Subtask load_salesorderdetail_from_s3_to_redshift
[2021-06-07 01:32:59,686] {logging_mixin.py:104} INFO - Running <TaskInstance: stage_rox_bike_tables.load_salesorderdetail_from_s3_to_redshift 2021-06-07T01:31:57.496009+00:00 [running]> on host 21bd802337aa
[2021-06-07 01:32:59,720] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=stage_rox_bike_tables
AIRFLOW_CTX_TASK_ID=load_salesorderdetail_from_s3_to_redshift
AIRFLOW_CTX_EXECUTION_DATE=2021-06-07T01:31:57.496009+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-06-07T01:31:57.496009+00:00
[2021-06-07 01:32:59,726] {connection.py:360} ERROR - Failed parsing the json for conn_id redshift
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 357, in extra_dejson
    obj = json.loads(self.extra)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2021-06-07 01:32:59,727] {base.py:78} INFO - Using connection to: id: redshift. Host: doxcluster.craeubgpe2r5.us-east-1.redshift.amazonaws.com, Port: 5439, Schema: dox, Login: doxuser, Password: ***, extra: {}
[2021-06-07 01:32:59,727] {connection.py:360} ERROR - Failed parsing the json for conn_id redshift
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 357, in extra_dejson
    obj = json.loads(self.extra)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2021-06-07 01:32:59,727] {connection.py:360} ERROR - Failed parsing the json for conn_id redshift
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 357, in extra_dejson
    obj = json.loads(self.extra)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2021-06-07 01:32:59,727] {connection.py:360} ERROR - Failed parsing the json for conn_id redshift
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 357, in extra_dejson
    obj = json.loads(self.extra)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2021-06-07 01:33:01,478] {dbapi.py:204} INFO - Running statement: 
COPY SalesOrderDetail
FROM 's3://roxproject/data/Sales.SalesOrderDetail.csv'
IAM_ROLE 'arn:aws:iam::029258854698:role/doxRole'
IGNOREHEADER 1
DELIMITER ';', parameters: None
[2021-06-07 01:33:04,041] {python.py:151} INFO - Done. Returned value was: None
[2021-06-07 01:33:04,046] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=stage_rox_bike_tables, task_id=load_salesorderdetail_from_s3_to_redshift, execution_date=20210607T013157, start_date=20210607T013259, end_date=20210607T013304
[2021-06-07 01:33:04,067] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-06-07 01:33:04,087] {local_task_job.py:151} INFO - Task exited with return code 0
