[2021-06-07 01:13:24,654] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: create_rox_tables.create_salesorderdetail_table 2021-06-07T01:13:01.418941+00:00 [queued]>
[2021-06-07 01:13:24,668] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: create_rox_tables.create_salesorderdetail_table 2021-06-07T01:13:01.418941+00:00 [queued]>
[2021-06-07 01:13:24,668] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-07 01:13:24,669] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-06-07 01:13:24,671] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-07 01:13:24,680] {taskinstance.py:1087} INFO - Executing <Task(PostgresOperator): create_salesorderdetail_table> on 2021-06-07T01:13:01.418941+00:00
[2021-06-07 01:13:24,689] {standard_task_runner.py:52} INFO - Started process 236 to run task
[2021-06-07 01:13:24,691] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'create_rox_tables', 'create_salesorderdetail_table', '2021-06-07T01:13:01.418941+00:00', '--job-id', '59', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/create_rox_tables.py', '--cfg-path', '/tmp/tmp0pikep39', '--error-file', '/tmp/tmpi_6urhqt']
[2021-06-07 01:13:24,691] {standard_task_runner.py:77} INFO - Job 59: Subtask create_salesorderdetail_table
[2021-06-07 01:13:24,727] {logging_mixin.py:104} INFO - Running <TaskInstance: create_rox_tables.create_salesorderdetail_table 2021-06-07T01:13:01.418941+00:00 [running]> on host 21bd802337aa
[2021-06-07 01:13:24,769] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_rox_tables
AIRFLOW_CTX_TASK_ID=create_salesorderdetail_table
AIRFLOW_CTX_EXECUTION_DATE=2021-06-07T01:13:01.418941+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-06-07T01:13:01.418941+00:00
[2021-06-07 01:13:24,769] {postgres.py:70} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS SalesOrderDetail
    (
        SalesOrderID INTEGER NOT NULL,
        SalesOrderDetailID INTEGER NOT NULL,
        CarrierTrackingNumber VARCHAR(20),
        OrderQty INTEGER,
        ProductID INTEGER,
        SpecialOfferID INTEGER,
        UnitPrice FLOAT,
        UnitPriceDiscount FLOAT,
        LineTotal FLOAT,
        rowguid VARCHAR(36),
        ModifiedDate TIMESTAMP,
        PRIMARY KEY (SalesOrderID, SalesOrderDetailID),
        FOREIGN KEY (SalesOrderID)
            REFERENCES SalesOrderHeader(SalesOrderID),
        FOREIGN KEY (SpecialOfferID, ProductID)
            REFERENCES SpecialOfferProduct(SpecialOfferID, ProductID),
        FOREIGN KEY (ProductID)
            REFERENCES Product(ProductID)
    )
[2021-06-07 01:13:24,778] {connection.py:360} ERROR - Failed parsing the json for conn_id redshift
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 357, in extra_dejson
    obj = json.loads(self.extra)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2021-06-07 01:13:24,779] {base.py:78} INFO - Using connection to: id: redshift. Host: doxcluster.craeubgpe2r5.us-east-1.redshift.amazonaws.com, Port: 5439, Schema: dox, Login: doxuser, Password: ***, extra: {}
[2021-06-07 01:13:24,779] {connection.py:360} ERROR - Failed parsing the json for conn_id redshift
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 357, in extra_dejson
    obj = json.loads(self.extra)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2021-06-07 01:13:24,780] {connection.py:360} ERROR - Failed parsing the json for conn_id redshift
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 357, in extra_dejson
    obj = json.loads(self.extra)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2021-06-07 01:13:24,780] {connection.py:360} ERROR - Failed parsing the json for conn_id redshift
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 357, in extra_dejson
    obj = json.loads(self.extra)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2021-06-07 01:13:26,283] {dbapi.py:204} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS SalesOrderDetail
    (
        SalesOrderID INTEGER NOT NULL,
        SalesOrderDetailID INTEGER NOT NULL,
        CarrierTrackingNumber VARCHAR(20),
        OrderQty INTEGER,
        ProductID INTEGER,
        SpecialOfferID INTEGER,
        UnitPrice FLOAT,
        UnitPriceDiscount FLOAT,
        LineTotal FLOAT,
        rowguid VARCHAR(36),
        ModifiedDate TIMESTAMP,
        PRIMARY KEY (SalesOrderID, SalesOrderDetailID),
        FOREIGN KEY (SalesOrderID)
            REFERENCES SalesOrderHeader(SalesOrderID),
        FOREIGN KEY (SpecialOfferID, ProductID)
            REFERENCES SpecialOfferProduct(SpecialOfferID, ProductID),
        FOREIGN KEY (ProductID)
            REFERENCES Product(ProductID)
    ), parameters: None
[2021-06-07 01:13:27,162] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=create_rox_tables, task_id=create_salesorderdetail_table, execution_date=20210607T011301, start_date=20210607T011324, end_date=20210607T011327
[2021-06-07 01:13:27,228] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-06-07 01:13:27,268] {local_task_job.py:151} INFO - Task exited with return code 0
