[2021-06-07 01:32:20,002] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: stage_rox_bike_tables.create_salesorderheader_table 2021-06-07T01:31:57.496009+00:00 [queued]>
[2021-06-07 01:32:20,013] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: stage_rox_bike_tables.create_salesorderheader_table 2021-06-07T01:31:57.496009+00:00 [queued]>
[2021-06-07 01:32:20,013] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-07 01:32:20,013] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-06-07 01:32:20,016] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-07 01:32:20,027] {taskinstance.py:1087} INFO - Executing <Task(PostgresOperator): create_salesorderheader_table> on 2021-06-07T01:31:57.496009+00:00
[2021-06-07 01:32:20,035] {standard_task_runner.py:52} INFO - Started process 177 to run task
[2021-06-07 01:32:20,037] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'stage_rox_bike_tables', 'create_salesorderheader_table', '2021-06-07T01:31:57.496009+00:00', '--job-id', '69', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/stage_data_s3_to_redshift.py', '--cfg-path', '/tmp/tmpwzogkc31', '--error-file', '/tmp/tmpuuhqqnqq']
[2021-06-07 01:32:20,037] {standard_task_runner.py:77} INFO - Job 69: Subtask create_salesorderheader_table
[2021-06-07 01:32:20,063] {logging_mixin.py:104} INFO - Running <TaskInstance: stage_rox_bike_tables.create_salesorderheader_table 2021-06-07T01:31:57.496009+00:00 [running]> on host 21bd802337aa
[2021-06-07 01:32:20,096] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=stage_rox_bike_tables
AIRFLOW_CTX_TASK_ID=create_salesorderheader_table
AIRFLOW_CTX_EXECUTION_DATE=2021-06-07T01:31:57.496009+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-06-07T01:31:57.496009+00:00
[2021-06-07 01:32:20,096] {postgres.py:70} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS SalesOrderHeader
    (
        SalesOrderID INTEGER NOT NULL,
        RevisionNumber INTEGER,
        OrderDate TIMESTAMP,
        DueDate TIMESTAMP,
        ShipDate TIMESTAMP,
        Status INTEGER,
        OnlineOrderFlag INTEGER,
        SalesOrderNumber VARCHAR(10),
        PurchaseOrderNumber VARCHAR(20),
        AccountNumber VARCHAR(20),
        CustomerID INTEGER,
        SalesPersonID INTEGER,
        TerritoryID INTEGER,
        BillToAddressID INTEGER,
        ShipToAddressID INTEGER,
        ShipMethodID INTEGER,
        CreditCardID INTEGER,
        CreditCardApprovalCode VARCHAR(20),
        CurrencyRateID INTEGER,
        SubTotal FLOAT,
        TaxAmt FLOAT,
        Freight FLOAT,
        TotalDue FLOAT,
        Comment VARCHAR(10),
        rowguid VARCHAR(36),
        ModifiedDate TIMESTAMP,
        PRIMARY KEY (SalesOrderID),
        FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)
    )
[2021-06-07 01:32:20,104] {connection.py:360} ERROR - Failed parsing the json for conn_id redshift
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 357, in extra_dejson
    obj = json.loads(self.extra)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2021-06-07 01:32:20,105] {base.py:78} INFO - Using connection to: id: redshift. Host: doxcluster.craeubgpe2r5.us-east-1.redshift.amazonaws.com, Port: 5439, Schema: dox, Login: doxuser, Password: ***, extra: {}
[2021-06-07 01:32:20,105] {connection.py:360} ERROR - Failed parsing the json for conn_id redshift
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 357, in extra_dejson
    obj = json.loads(self.extra)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2021-06-07 01:32:20,106] {connection.py:360} ERROR - Failed parsing the json for conn_id redshift
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 357, in extra_dejson
    obj = json.loads(self.extra)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2021-06-07 01:32:20,106] {connection.py:360} ERROR - Failed parsing the json for conn_id redshift
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 357, in extra_dejson
    obj = json.loads(self.extra)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2021-06-07 01:32:21,641] {dbapi.py:204} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS SalesOrderHeader
    (
        SalesOrderID INTEGER NOT NULL,
        RevisionNumber INTEGER,
        OrderDate TIMESTAMP,
        DueDate TIMESTAMP,
        ShipDate TIMESTAMP,
        Status INTEGER,
        OnlineOrderFlag INTEGER,
        SalesOrderNumber VARCHAR(10),
        PurchaseOrderNumber VARCHAR(20),
        AccountNumber VARCHAR(20),
        CustomerID INTEGER,
        SalesPersonID INTEGER,
        TerritoryID INTEGER,
        BillToAddressID INTEGER,
        ShipToAddressID INTEGER,
        ShipMethodID INTEGER,
        CreditCardID INTEGER,
        CreditCardApprovalCode VARCHAR(20),
        CurrencyRateID INTEGER,
        SubTotal FLOAT,
        TaxAmt FLOAT,
        Freight FLOAT,
        TotalDue FLOAT,
        Comment VARCHAR(10),
        rowguid VARCHAR(36),
        ModifiedDate TIMESTAMP,
        PRIMARY KEY (SalesOrderID),
        FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)
    ), parameters: None
[2021-06-07 01:32:22,468] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=stage_rox_bike_tables, task_id=create_salesorderheader_table, execution_date=20210607T013157, start_date=20210607T013220, end_date=20210607T013222
[2021-06-07 01:32:22,499] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-07 01:32:22,534] {local_task_job.py:151} INFO - Task exited with return code 0
